# Site settings
title: Fiveneves
SEOTitle: Fiveneves's blog
description: Fiveneves's blog.
keyword: "blog, personal website"
url: "https://fiveneves.github.io"      # your host, for absolute URL
baseurl: ""                                         # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/header-avatar.jpg"                    # the avatar showing on the homepage


# GitHub repository (if the site is hosted by GitHub)
repository: Fiveneves/Fiveneves.github.io
repository_branch: main


# Theme style settings
theme_style:
  highlight:    # "dark" (default), "light"
  alert:        # "flat" (default), "modern"
  post_preview: # "image" (default), "text"
                # display post's featured image on homepage or not


# Markdown enhancements settings
math:
  enable: true    # false (default), true
                  # math rendering for all posts and keynotes
  engine: mathjax      
                  # "katex" (default), "mathjax"
                  # only make sense when `math.engine: true`
chart: true       # false (default), true
mermaid: true     # false (default), true
emoji-plus: true  # false (default), true


# CDN settings
cdn:
  source:       # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable:       # false (default), true
                # optimizing asset files via jsDelivr or not


# Publish posts or collection documents with a future date.
future: true

collections:
  experiences:
    output: true
  publications:
    output: true
  projects:
    output: true


# SNS settings
sns:
  RSS: true
  github_username: Fiveneves
  weibo_username:
  zhihu_username: 
  twitter_username: 
  facebook_username: 
  linkedin_username: 
  email_address: 


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true  # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN

# Gems
# you have to `bundle config set path 'vendor/bundle' && bundle install` before local preview
plugins:
  - jekyll-paginate
  - jemoji


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true                  # we use highlight.js for syntax highlighting, so we disable rouge here


# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-id-card-o
    submenus:
      - title: Me
        font: fas fa-user-circle-o
        url: /about/
      - title: Theme
        font: fas fa-file-text
        url: /theme/
  - title: Archive
    font: fas fa-archive
    url: /archive/
  - title: Links
    font: fas fa-link
    url: /links/


# Comment settings
comment:
  # active: utterances # 使用github issue作为文章的评论系统
  #   utterances:
  #     repo: fiveneves.github.io        # <gh-username>/<repo>
  #     issue_term: title  # < url | pathname | title | ...>
  # paginate: 20
  provider: gitalk # false (default), "disqus", "gitalk", "valine"

  # Gitalk settings
  # https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    githubID: Fiveneves
    clientID: 'f6cf3058e6bb5ed13ae3'
    clientSecret: '3da0d7ded3205425e02e94f94a66c74b69a65c64'
    repo: Fiveneves.github.io
    owner: Fiveneves
    admin:
      - Fiveneves
    distractionFreeMode: true

# Disqus settings
#   disqus_username: Fiveneves

  # Valine settings
  # https://valine.js.org/
  valine:
    appID:
    appKey:


# Analytics settings
analytics:
  # Baidu Analytics
  ba_track_id: 00504d7a0bf51278aa92b36e60e830b5 # [your baidu track id]

  # Google Analytics
  ga_track_id: 'G-ZYM02DSEHS'               # [your google track id]


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: true # default: false
